version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      SA_PASSWORD: "konecta2025"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - erp-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - erp-network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - erp-network

  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    command: agent -server -bootstrap -ui -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - erp-network

  config-server:
    build:
      context: backend/config
      dockerfile: Dockerfile
    container_name: config-server
    environment:
      SERVER_PORT: 8888
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - consul
    ports:
      - "8888:8888"
    networks:
      - erp-network

  api-gateway:
    build:
      context: backend/ApiGateWay
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      CONFIG_SERVER_URI: http://config-server:8888
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_SERVICE_HOST: api-gateway
      AUTH_SERVICE_URI: http://authentication-service:7280
      HR_SERVICE_URI: http://hr-service:5005
      USER_MANAGEMENT_SERVICE_URI: http://user-management-service:5078
      INVENTORY_SERVICE_URI: http://inventory-service:5020
      FINANCE_SERVICE_URI: http://finance-service:5003
      REPORTING_SERVICE_URI: http://reporting-service:8085
    depends_on:
      - config-server
      - authentication-service
      - hr-service
      - user-management-service
      - inventory-service
      - finance-service
      - reporting-service
    ports:
      - "8080:8080"
    networks:
      - erp-network

  reporting-service:
    build:
      context: backend/ReportingService
      dockerfile: Dockerfile
    container_name: reporting-service
    environment:
      CONFIG_SERVER_URI: http://config-server:8888
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_SERVICE_HOST: reporting-service
      FINANCE_SERVICE_URI: http://finance-service:5003
      HR_SERVICE_URI: http://hr-service:5005
      INVENTORY_SERVICE_URI: http://inventory-service:5020
    depends_on:
      - config-server
      - finance-service
      - hr-service
      - inventory-service
    ports:
      - "8085:8085"
    networks:
      - erp-network

  authentication-service:
    build:
      context: .
      dockerfile: backend/AuthenticationService/Dockerfile
    container_name: authentication-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=Konecta_Auth;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      Email__SmtpHost: mailhog
      Consul__Host: http://consul:8500
      ServiceConfig__Host: 0.0.0.0
      ServiceConfig__Port: 7280
      ServiceConfig__Scheme: http
      ServiceConfig__RegisterWithConsul: "true"
    depends_on:
      - sqlserver
      - rabbitmq
      - mailhog
      - consul
    ports:
      - "7280:7280"
    networks:
      - erp-network

  hr-service:
    build:
      context: .
      dockerfile: backend/HrService/Dockerfile
    container_name: hr-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=Konecta_Hr;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      Consul__Host: http://consul:8500
      ServiceConfig__Host: 0.0.0.0
      ServiceConfig__Port: 5005
      ServiceConfig__RegisterWithConsul: "true"
    depends_on:
      - sqlserver
      - rabbitmq
      - consul
    ports:
      - "5005:5005"
    networks:
      - erp-network

  inventory-service:
    build:
      context: .
      dockerfile: backend/InventoryService/Dockerfile
    container_name: inventory-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=Konecta_Inventory;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      Consul__Host: http://consul:8500
      ServiceConfig__Host: 0.0.0.0
      ServiceConfig__Port: 5020
      ServiceConfig__RegisterWithConsul: "true"
    depends_on:
      - sqlserver
      - consul
    ports:
      - "5020:5020"
    networks:
      - erp-network

  finance-service:
    build:
      context: .
      dockerfile: backend/FinanceService/Dockerfile
    container_name: finance-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=Konecta_Finance;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      Consul__Host: http://consul:8500
      ServiceConfig__Host: 0.0.0.0
      ServiceConfig__Port: 5003
      ServiceConfig__RegisterWithConsul: "true"
    depends_on:
      - sqlserver
      - consul
    ports:
      - "5003:5003"
    networks:
      - erp-network

  user-management-service:
    build:
      context: .
      dockerfile: backend/UserManagementService/Dockerfile
    container_name: user-management-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=Konecta_UserManagement;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      Consul__Host: http://consul:8500
      ServiceConfig__Host: 0.0.0.0
      ServiceConfig__Port: 5078
      ServiceConfig__RegisterWithConsul: "true"
    depends_on:
      - sqlserver
      - rabbitmq
      - consul
    ports:
      - "5078:5078"
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  sqlserver-data:
