server:
  port: 8085

spring:
  application:
    name: reporting-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: ${CONSUL_REGISTER:true}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${random.value}
        hostname: ${CONSUL_SERVICE_HOST:host.docker.internal}
        prefer-ip-address: false
        health-check-path: /actuator/health
        health-check-interval: 15s
      config:
        enabled: false

services:
  finance:
    # will be @FeignClient(name = "finance-service") for service discovery later
    url: http://localhost:5003
  hr:
    # will be @FeignClient(name = "hr-service") for service discovery later
    url: http://localhost:5001
  inventory:
    # will be @FeignClient(name = "inventory-service") for service discovery later
    url: http://localhost:5004

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
